name: 'Lint Code'
on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Print Working Directory
        run: pwd
      
      - name: Run Flake8 Linter
        run: |
          # This command finds all Python files recursively and runs flake8 on them
          find . -name "*.py" -exec flake8 {} +
          echo "Linted all the Python files successfully"

  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Updated to a more recent LTS version

      - name: Install Node.js Dependencies
        run: |
          # Ensure that package.json is present and install dependencies
          if [ -f package.json ]; then
            npm install
          else
            echo "Error: package.json file not found!"
            exit 1
          fi

      - name: Install ESLint and JSHint
        run: |
          npm install -g jshint eslint
          
      - name: Configure ESLint
        run: |
          echo '{
            "env": {
              "es6": true,
              "node": true
            },
            "extends": [
              "eslint:recommended",
              "airbnb-base"
            ],
            "parserOptions": {
              "ecmaVersion": 2021,
              "sourceType": "module"
            },
            "rules": {}
          }' > .eslintrc.js

      - name: Run JSHint Linter
        run: |
          # This command finds all JavaScript files recursively and runs JSHint on them
          find ./server/database -name "*.js" -exec jshint {} +
          echo "Linted all the JavaScript files successfully"
      
      - name: Run ESLint
        run: |
          # Run ESLint on the JavaScript files in the project
          npx eslint . --ext .js
          echo "Linted all the JavaScript files successfully"
